config/routes.rb
Spree::Core::Engine.routes.draw do
    namespace :admin do
    	resources :wished_products
    end
end

app/models/spree/stock_movement_decorator.rb
Spree::StockMovement.class_eval do
	def notify_stock_updated(users,variant)
      Spree::StockMailer.notify_users_email(users,variant).deliver
    end
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do

  include ActionView::Helpers::NumberHelper

  def to_hash
    actual_price  = self.price
    {
      :id    => self.id,
      :in_stock => self.in_stock?,
      :can_supply => self.can_supply?,
      :price => number_to_currency(actual_price),
      :preorder => self.product.preorder
    }
  end

end

app/models/spree/wished_product_decorator.rb
Spree::WishedProduct.class_eval do
  	def notify_user(user,variant_id)
     	Spree::WishedProductMailer.notify_user(user,variant_id).deliver
    end
end

app/controllers/spree/admin/stock_items_controller_decorator.rb
Spree::Admin::StockItemsController.class_eval do
	def create
        variant = Spree::Variant.find(params[:variant_id])
        stock_location = Spree::StockLocation.find(params[:stock_location_id])
        stock_movement = stock_location.stock_movements.build(stock_movement_params)
        stock_movement.stock_item = stock_location.set_up_stock_item(variant)

        users = select_users_want_wished_variant
        if users.present? && variant && stock_movement.stock_item.count_on_hand < 1 && !variant.can_supply?
        	stock_movement.notify_stock_updated(users, variant)
        end

        if stock_movement.save
          flash[:success] = flash_message_for(stock_movement, :successfully_created)
        else
          flash[:error] = Spree.t(:could_not_create_stock_movement)
        end

        redirect_to :back
    end
    private

    def select_users_want_wished_variant
    	users = []
    	Spree::Wishlist.all.each do |wishlist|
    		wishlist.wished_products.each do |product|
    			if product.variant_id == params[:variant_id].to_i
    				users << wishlist.user
    			end
    		end
    	end
    	return users
    end
end

app/controllers/spree/admin/wished_products_controller.rb
module Spree
	module Admin
		class WishedProductsController < Spree::Admin::BaseController
			def index
				@collection = Spree::WishedProduct.order(created_at: :desc).group(:variant_id).select(:id, :variant_id, "COUNT(spree_wished_products.variant_id) as times_wished").page(params[:page]).per(20)
			end
		end
	end
end

app/controllers/spree/wished_products_controller_decorator.rb
Spree::WishedProductsController.class_eval do
  def create
    @wished_product = Spree::WishedProduct.new(wished_product_attributes)
    @wishlist = spree_current_user.wishlist

    if @wishlist.include? params[:wished_product][:variant_id]
      @wished_product = @wishlist.wished_products.detect {|wp| wp.variant_id == params[:wished_product][:variant_id].to_i }
    else
      @wished_product.wishlist = spree_current_user.wishlist
      @wished_product.save
    end

    @wished_product.notify_user(spree_current_user,params[:wished_product][:variant_id])

    respond_with(@wished_product) do |format|
      format.html { redirect_to wishlist_url(@wishlist) }
    end
  end
end

app/helpers/spree/base_helper_decorator.rb
Spree::BaseHelper.module_eval do
  def can_supply_variants(product)
      cache_key = "supply-variants-#{product.id}-#{product.updated_at}"
      Rails.cache.fetch("#{cache_key}/can_supply_product", expires_in: 6.hours) do
        product.variants.each do |variant|
          if variant.can_supply?
            return true
          end
        end
        return false
      end
  end
end

app/views/spree/admin/wished_products/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:wished_products) %>
<% end %>


<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= paginate @collection %>

<% if @collection.any? %>
  <table class="index" id="listing_widhed_products">
    <colgroup>
       <col style="width: 15%;">
       <col style="width: 10%;">
       <col style="width: 48%;">
       <col style="width: 10%;">
       <col style="width: 17%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= Spree.t(:sku) %></th>
        <th colspan="2"><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:times_wished) %></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |wished_product| %>
          <tr id="<%= spree_dom_id wished_product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <td class="align-center"><%= wished_product.variant.sku rescue '' %></td>
            <td class="align-center"><%= mini_image(wished_product.variant.product) %></td>
            <td><%= link_to wished_product.variant.product.try(:name), edit_admin_product_path(wished_product.variant.product) %></td>
            <td class="align-center"><%= wished_product.times_wished %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/product')) %>
  </div>
<% end %>

<%= paginate @collection %>

app/views/spree/products/_wishlist_form.html.erb
<% if spree_current_user %>
	<div id="wishlist-form">
		<%= form_for Spree::WishedProduct.new do |f| %>
			<%= f.hidden_field :variant_id, :value => @product.master.id %>
			<button type="submit" class="btn btn-success">
				<%= Spree.t(:add_to_wishlist) %>
			</button>
		<% end %>
	</div>
<% else %>
	<div id="wishlist-form">
		<%= link_to Spree.t(:add_to_wishlist), spree.signup_path, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/spree/wishlists/show.html.erb
<div id="wishlist_header" class="row">
  <h1><%= @wishlist.name %></h1>
</div>
<table id="wishlist">
  <thead>
    <tr>
      <% if @wishlist.user == spree_current_user %>
        <th class='col-md-2'><%= Spree.t(:wishlist_actions) %></th>
      <% end -%>
      <th class='col-md-2'><%= Spree.t(:item_view) %></th>
      <th class='col-md-4 hidden-xs'><%= Spree.t(:item_description) %></th>
      <th class='col-md-1'><%= Spree.t(:availability) %></th>
      <th class='col-md-2'><%= Spree.t(:date_added) %></th>
      <th class='col-md-1'><%= Spree.t(:price) %></th>
    </tr>
  </thead>
  <tbody id="line_items">
  <% if @wishlist.wished_products.size > 0 %>
    <% @wishlist.wished_products.each do |wish|
        variant = wish.variant
        product = variant.product %>
    <tr class="<%= cycle('', 'alt') %>">
    <% if @wishlist.user == spree_current_user %>
      <td class='col-md-2'>
        <p><%= link_to Spree.t(:remove_from_wishlist), wish, :method => :delete %></p>
        <div id="cart-form">
          <%= form_for :order, :url => spree.populate_orders_url, remote: true do |f| %>
            <%= hidden_field_tag "variant_id", variant.id, :size => 3 %>
            <%= hidden_field_tag "quantity", 1, :size => 3 %>
            <% if variant.can_supply? %>
              <%= link_to Spree.t(:add_to_cart), '#', :id => 'add-to-cart-button', :onclick => "$(this).parent().submit(); return false;" %>
             <% end %>
          <% end %>
        </div>
        <% if spree_current_user.wishlists.count > 1 %>
          <%= Spree.t(:move_to_another_wishlist) %>:
          <%= form_for wish do |f| %>
            <%= f.select :wishlist_id, spree_current_user.wishlists.map{|wl| [wl.name, wl.id]} %>
            <%= f.submit Spree.t(:move) %>
          <% end %>
        <% end %>
        <br />
      </td>
    <% end -%>
      <td class='col-md-2'>
        <% if variant.images.length == 0 %>
          <%= small_image(variant.product) %>
        <% else %>
          <%= image_tag variant.images.first.attachment.url(:small) %>
        <% end %>
      </td>
      <td class='col-md-4 hidden-xs'>
        <h4><%= link_to product.name, product %></h4>
        <p><%= variant_options variant %></p>
        <%= product_description(product) %>
      </td>
      <td class='col-md-1'>
        <%= variant.can_supply? ? Spree.t(:in_stock) : Spree.t(:out_of_stock) %>
      </td>
      <td class='col-md-2'>
        <%= wish.created_at.strftime "%m/%d/%Y" %>
      </td>
      <td class='col-md-1'>
        <%= display_price(variant) %>
      </td>
    </tr>
    <% end -%>
  <% else -%>
    <tr>
      <td colspan="6"><%= Spree.t(:your_wishlist_is_empty) %></td>
    </tr>
  <% end -%>
  </tbody>
</table>
<div class="footer_links" data-hook="wishlist_footer_links">
<%= link_to Spree.t(:continue_shopping), seo_url(Spree::Taxon.first), :class => "btn btn-success" %>
</div>